# Dockerfile (web)
FROM python:3.11-slim

# system deps for common python libs
RUN apt-get update && apt-get install -y build-essential libpq-dev curl && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]
